### ISSUE TITLE
tou2 (头, 投) listed as CGV instead of CVV

### ISSUE THREAD

**Issue by roryturnbull** [karlneergaard/Database_of_word-level_statistics#1]
In ``C_G_V_C_T.txt`` the word _tou2_ (头, 投) is listed as having a CGV syllable structure, but it ought to be CVV. This also affects compounds with this word, e.g. _tou2 fa3_ (头发), _tou2 piao4_ (投票), _hui2 tou2_ (回头), _jing4 tou2_ (镜头), and _tou2 ru4_ (投入). This does not appear to affect other instances of _ou_. This error also appears in at least one other file, but I haven't checked systematically.

**Comment by roryturnbull** [comment]
Actually, I spoke too soon: it looks like every instance of _tou_ and _pou_ is affected!

**Comment by karlneergaard** [comment]
Thanks for pointing this out! In this latest update (2020/05/15) we've fixed the Systruct error you found and some errors that were in the frequency list
